export const users = [
  {
    id: 1,
    name: "admin",
    lastName: "admin",
    password: "admin123",
    email: "admin",
    phone: "5555555555",
    role: "admin",
    created_at: "",
  },
  {
    id: 2,
    name: "yetkili",
    lastName: "yetkili",
    password: "yetkili123",
    email: "yetkili@library.com",
    phone: "5555555555",
    role: "librarian",
    created_at: "",
  },
  {
    id: 3,
    name: "Öğrenci",
    lastName: "Öğrenci",
    email: "student@library.com",
    phone: "5555555555",
    password: "123456",
    role: "student",
    created_at: "",
  },
];
